### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by zimbatm** [manifoldco/torus-cli#383] opened 2018-04-06 16:15 UTC
Hi,

It doesn't look like torus-cli supports a password reset functionality. If the original password is lost there is not way of restoring the account, even with the trade-off of loosing all the stored secrets.

Is this something that you are considering supporting in the future?

Thanks,
z

**Comment by arbourd** [comment] 2018-05-01 13:24
Duplicate of #144

**Closed** 2018-05-01 20:35 UTC
